numero = int(input("Digite um número: "))

print(f"A tabuada do número {numero} é: ")
print('=' * 20)
print(f"{numero} x 1 = {numero * 1:2}")
print(f"{numero} x 2 = {numero * 2:2}")
print(f"{numero} x 3 = {numero * 3:2}")
print(f"{numero} x 4 = {numero * 4:2}")
print(f"{numero} x 5 = {numero * 5:2}")
print(f"{numero} x 6 = {numero * 7:2}")
print(f"{numero} x 7 = {numero * 8:2}")
print(f"{numero} x 8 = {numero * 8:2}")
print(f"{numero} x 9 = {numero * 9:2}")
print(f"{numero} x 10 = {numero * 10:2}")
print('='*20)